import { useEffect, useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { fetchConfusionMatrix, fetchTrace, fetchTraces } from '../lib/api'
import SpanWaterfall from './SpanWaterfall'
import ConfusionMatrix from './ConfusionMatrix'
export default function TraceExplorer({ runId }: { runId: string }) {
  const [selected, setSelected] = useState(''); const [filter, setFilter] = useState(''); const [status, setStatus] = useState('all'); const [category, setCategory] = useState('all')
  const traces = useQuery({ queryKey: ['traces', runId], queryFn: () => fetchTraces(runId) })
  useEffect(() => {
    if (traces.data?.length && !traces.data.some(row => row.trace_id === selected)) setSelected(traces.data[0].trace_id)
    if (traces.data?.length === 0) setSelected('')
  }, [runId, traces.data, selected])
  const trace = useQuery({ queryKey: ['trace', runId, selected], queryFn: () => fetchTrace(selected), enabled: Boolean(selected) })
  const matrix = useQuery({ queryKey: ['matrix', runId], queryFn: () => fetchConfusionMatrix(runId) })
  const rows = (traces.data ?? []).filter(r => r.task_id.includes(filter) && (status === 'all' || r.status === status) && (category === 'all' || r.failure_class === category))
  return <div className="trace-layout"><section className="trace-list"><div className="tabs"><button className={status==='all'?'selected':''} onClick={()=>setStatus('all')}>All <small>{traces.data?.length ?? '—'}</small></button><button className={status==='failed'?'selected fail-text':''} onClick={()=>setStatus('failed')}>Failed <small>{traces.data?.filter(r=>r.status==='failed').length ?? '—'}</small></button><button className={status==='passed'?'selected pass-text':''} onClick={()=>setStatus('passed')}>Passed</button></div><div className="filters"><input placeholder="⌕  task_fx_" value={filter} onChange={e=>setFilter(e.target.value)}/><select aria-label="Failure category" value={category} onChange={e=>setCategory(e.target.value)}><option value="all">Cat: All</option>{['tool','retrieval','model','orchestration'].map(x=><option key={x} value={x}>{x}</option>)}</select></div><div className="trace-rows">{traces.isLoading ? <p className="state">Loading traces…</p> : traces.isError ? <p className="state fail-text">Could not load traces.</p> : rows.map(row=><button key={row.trace_id} onClick={()=>setSelected(row.trace_id)} className={`trace-row ${selected===row.trace_id?'chosen':''}`}><span className={row.status==='failed'?'status-dot fail':'status-dot pass'}/><b>task_{row.task_id}</b>{row.failure_class && <span className={`category ${row.failure_class}`}>{row.failure_class}</span>}<span className="duration">{row.duration_ms.toLocaleString()}ms</span><span className="muted">€{row.cost_eur.toFixed(4)}</span></button>)}</div>{matrix.data && <ConfusionMatrix data={matrix.data}/>}</section>
    <div className="trace-detail">{!selected && !traces.isLoading ? <div className="panel state">No traces found for this run.</div> : trace.isLoading ? <div className="panel state">Loading trace…</div> : trace.isError || !trace.data ? <div className="panel fail-text">Could not load trace.</div> : <>{(() => { const primary = trace.data.spans.find(s => s.span_id === trace.data.primary_failure_span_id); const selectedRow = traces.data?.find(r => r.trace_id === trace.data.trace_id); const attrs = primary?.attributes ?? {}; const failed = Boolean(trace.data.primary_failure_span_id); const attribution = failed ? (selectedRow?.failure_class ?? primary?.operation_name ?? 'failed') : 'passed'; return <><section className="panel trace-summary"><div><b className={failed ? 'fail-text' : 'pass-text'}>● &nbsp;task_{trace.data.task_id}</b><span className="muted"> · {trace.data.trace_id}</span><p className="muted">root_run_id: {runId} · agent session</p></div><span className={`badge ${failed ? 'fail' : 'pass'}`}>Status: {attribution}</span><span className="badge">Total spans: {selectedRow?.span_count ?? trace.data.spans.length}</span><span className="badge">Duration: {((selectedRow?.duration_ms ?? 0)/1000).toFixed(2)}s</span><span className="badge cost">Cost: €{(selectedRow?.cost_eur ?? 0).toFixed(4)}</span><button className="primary-button">↻ Re-execute</button></section><SpanWaterfall trace={trace.data}/><section className="panel selected-span"><div className="panel-head"><h2>Selected Span: <code>{primary?.name ?? '—'}</code></h2><span className={`badge ${failed ? 'fail' : 'pass'}`}>Attribution: {attribution}</span></div><div className="inspect-grid"><div><h3>GENAI & ENGINE CONTEXT</h3><p>operation: <b>{primary?.operation_name ?? '—'}</b></p><p>span id: <b>{primary?.span_id ?? '—'}</b></p></div><div><h3>TOKEN METRICS</h3><p>gen_ai.usage.prompt: <b>{primary?.tokens_in ?? '—'}{primary?.tokens_in == null ? '' : ' tok'}</b></p><p>gen_ai.usage.completion: <b>{primary?.tokens_out ?? '—'}{primary?.tokens_out == null ? '' : ' tok'}</b></p></div><div className="diagnostics"><h3>ERROR DIAGNOSTICS</h3><p>error.type: <b>{String(attrs['error.type'] ?? '—')}</b></p><p>error.message: <b>{String(attrs['error.message'] ?? '—')}</b></p></div></div><div className="notice">ⓘ &nbsp;Content capture is {trace.data.capture_tier === 'full' ? 'enabled' : 'disabled'} for active tier <b>{trace.data.capture_tier}</b>. {trace.data.capture_tier === 'full' ? 'Prompt and completion payloads may appear in span attributes.' : 'Prompt payload buffers and raw completion responses are omitted.'}</div></section></> })()}</>}</div>
  </div>
}
